---
title: "Section 4"
author: "Keely Kinnane"
date: "2024-04-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Section 4: Limitations

The methodological approach employed in our study necessitated the division of our dataset into distinct training and testing sets, each comprising half of the original data. Consequently, our analysis was conducted with a reduced sample size of 383 observations, further diminished to 333 after the removal of highly influential data points aimed at enhancing prediction accuracy. This reduction in sample size introduces several potential limitations. Notably, the selective removal of highly influential observations, while necessary for improving model accuracy, may result in an uneven representation of different demographic or spatial units within the dataset, potentially skewing the analysis towards over- or under-represented groups.

Moreover, a smaller sample size can yield less precise estimations of model parameters, accompanied by larger standard errors and wider confidence intervals for parameter estimates. This decrease in precision may hinder the ability to detect significant relationships between variables, thereby reducing the statistical power of hypothesis tests and increasing the likelihood of Type II errors.

In our model refinement process, we encountered a predictor with a variance inflation factor (VIF) slightly above the conventional threshold of 5. Despite this deviation, we retained the predictor in our final model, deciding that the slight increase in VIF suggested minimal collinearity concerns. Additionally, our assessment of normality via Q-Q plots revealed subtle deviations from the expected quantile line at the extremes, suggestive of a potentially heavy-tailed distribution. However, the majority of data points remained aligned with the expected distribution, and formal testing using the Shapiro-Wilks normality test corroborated the assumption of normality for error terms, reassuring us regarding the validity of our model assumptions.